[30;1m2023-04-10 02:22:58[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m Created websocket connected to wss://gateway.discord.gg/
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-d-32k7",{"micros":0.0}]']}}
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m Shard ID None has sent the IDENTIFY payload.
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m For Shard ID None: WebSocket Event: {'t': 'READY', 's': 1, 'op': 0, 'd': {'v': 10, 'user_settings': {}, 'user': {'verified': True, 'username': 'JPWP project', 'mfa_enabled': False, 'id': '1094609060051038359', 'global_name': None, 'flags': 0, 'email': None, 'display_name': None, 'discriminator': '7803', 'bot': True, 'avatar': '91946aaca3640ee4d2381495f517f8ca'}, 'session_type': 'normal', 'session_id': 'd8f381113d55e11928ebaacda7e09065', 'resume_gateway_url': 'wss://gateway-us-east1-d.discord.gg', 'relationships': [], 'private_channels': [], 'presences': [], 'guilds': [{'unavailable': True, 'id': '1094392308008484975'}], 'guild_join_requests': [], 'geo_ordered_rtc_regions': ['bucharest', 'frankfurt', 'milan', 'stockholm', 'rotterdam'], 'application': {'id': '1094609060051038359', 'flags': 565248}, '_trace': ['["gateway-prd-us-east1-d-32k7",{"micros":121317,"calls":["id_created",{"micros":2455,"calls":[]},"session_lookup_time",{"micros":388,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-blue-prd-2-141",{"micros":116690,"calls":["start_session",{"micros":78558,"calls":["discord-api-5fc54ccb5c-sbtql",{"micros":74450,"calls":["get_user",{"micros":23813},"get_guilds",{"micros":6378},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":44,"calls":[]},"presence_started",{"micros":27281,"calls":[]},"guilds_started",{"micros":75,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":10686,"calls":[]},"connect_finished",{"micros":10691,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":19,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']}}
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.client[0m Dispatching event socket_event_type
[30;1m2023-04-10 02:22:59[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: d8f381113d55e11928ebaacda7e09065).
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.client[0m Dispatching event connect
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'premium_subscription_count': 0, 'embedded_activities': [], 'emojis': [], 'description': None, 'banner': None, 'large': False, 'application_id': None, 'afk_channel_id': None, 'afk_timeout': 300, 'default_message_notifications': 0, 'unavailable': False, 'member_count': 3, 'max_members': 500000, 'nsfw_level': 0, 'stickers': [], 'features': [], 'splash': None, 'lazy': True, 'joined_at': '2023-04-09T13:37:25.533000+00:00', 'verification_level': 0, 'preferred_locale': 'en-US', 'latest_onboarding_question_id': None, 'hub_type': None, 'id': '1094392308008484975', 'home_header': None, 'vanity_url_code': None, 'premium_tier': 0, 'rules_channel_id': None, 'system_channel_flags': 0, 'threads': [], 'nsfw': False, 'max_stage_video_channel_users': 50, 'members': [{'user': {'username': 'JPWP project', 'public_flags': 0, 'id': '1094609060051038359', 'display_name': None, 'discriminator': '7803', 'bot': True, 'avatar_decoration': None, 'avatar': '91946aaca3640ee4d2381495f517f8ca'}, 'roles': ['1094617065580666965'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2023-04-09T13:37:25.533000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}], 'channels': [{'version': 1680993859139, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'Kana≈Çy tekstowe', 'id': '1094392308008484976', 'flags': 0}, {'version': 1680993859144, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'Kana≈Çy g≈Çosowe', 'id': '1094392308008484977', 'flags': 0}, {'version': 1680993859147, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '1094392308008484976', 'name': 'og√≥lny', 'last_message_id': '1094770522950217839', 'id': '1094392308008484978', 'flags': 0}, {'version': 1680993859157, 'user_limit': 0, 'type': 2, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '1094392308008484977', 'name': 'Og√≥lne', 'last_message_id': None, 'id': '1094392308008484979', 'flags': 0, 'bitrate': 64000}, {'version': 1681076622713, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '1094413640146354176', 'deny': '0', 'allow': '0'}, {'type': 0, 'id': '1094392308008484975', 'deny': '1024', 'allow': '0'}], 'parent_id': '1094392308008484976', 'nsfw': False, 'name': 'test', 'last_message_id': '1094779085479223448', 'id': '1094739395988435075', 'flags': 0}], 'owner_id': '224223341362413580', 'mfa_level': 0, 'public_updates_channel_id': None, 'presences': [], 'roles': [{'version': 1680993859135, 'unicode_emoji': None, 'tags': {}, 'position': 0, 'permissions': '67042396327489', 'name': '@everyone', 'mentionable': False, 'managed': False, 'id': '1094392308008484975', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1681080289373, 'unicode_emoji': None, 'tags': {}, 'position': 3, 'permissions': '0', 'name': 'Mateusz', 'mentionable': False, 'managed': False, 'id': '1094413640146354176', 'icon': None, 'hoist': False, 'flags': 0, 'color': 3447003}, {'version': 1681080289369, 'unicode_emoji': None, 'tags': {}, 'position': 2, 'permissions': '0', 'name': 'Maja', 'mentionable': False, 'managed': False, 'id': '1094413731921924186', 'icon': None, 'hoist': False, 'flags': 0, 'color': 15277667}, {'version': 1681080289567, 'unicode_emoji': None, 'tags': {'bot_id': '1094609060051038359'}, 'position': 1, 'permissions': '8', 'name': 'JPWP project', 'mentionable': False, 'managed': True, 'id': '1094617065580666965', 'icon': None, 'hoist': False, 'flags': 0, 'color': 15844367}], 'premium_progress_bar_enabled': False, 'region': 'deprecated', 'stage_instances': [], 'safety_alerts_channel_id': None, 'explicit_content_filter': 0, 'max_video_channel_users': 25, 'application_command_counts': {}, 'guild_hashes': {'version': 1, 'roles': {'omitted': False, 'hash': 'HNbeoA'}, 'metadata': {'omitted': False, 'hash': 'cCFFnA'}, 'channels': {'omitted': False, 'hash': '3/behA'}}, 'discovery_splash': None, 'name': 'JPWP project', 'icon': None, 'voice_states': [], 'guild_scheduled_events': [], 'system_channel_id': '1094392308008484978'}}
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.client[0m Dispatching event socket_event_type
[30;1m2023-04-10 02:22:59[0m [40;1mDEBUG   [0m [35mdiscord.client[0m Dispatching event guild_available
[30;1m2023-04-10 02:23:01[0m [40;1mDEBUG   [0m [35mdiscord.client[0m Dispatching event ready
[30;1m2023-04-10 02:23:40[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m Keeping shard ID None websocket alive with sequence 2.
[30;1m2023-04-10 02:23:40[0m [40;1mDEBUG   [0m [35mdiscord.gateway[0m For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2023-04-10 02:24:18] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:24:18] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:24:18] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:24:18[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:24:20[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 10cb977b054d343ce478ad2098ac3576).
[2023-04-10 02:25:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:25:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:25:59] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:25:59[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:26:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ea16126bc792580a03dd939f562ba554).
[2023-04-10 02:29:54] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:29:54] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:29:54] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:29:54[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:29:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 9f66d1be300776213e8b4f0f2234bfb5).
[2023-04-10 02:30:13] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:30:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:30:13] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:30:13[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:30:13[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 949375768d39cd959d6d9119a8d7d048).
[2023-04-10 02:31:02] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:31:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:31:02] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:31:02[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:31:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 79b3d3756aed76fe265d33f5a2719588).
[2023-04-10 02:31:26] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:31:26] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:31:26] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:31:26[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:31:27[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 2ad0486912f565e679c10078fc7fdbce).
[2023-04-10 02:32:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 02:32:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 02:32:21] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 02:32:21[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 02:32:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 873e1e9a62f7daa69441c7ff49eb7c91).
[2023-04-10 22:02:38] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-10 22:02:38] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-10 22:02:38] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-10 22:02:38[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-10 22:02:39[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 35feb12e4c7f5e2fcbe2e809fe538ff3).
[2023-04-11 00:12:12] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:12:12] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:12:12] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:12:12[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:12:13[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 3fe3a8c89f8c07830d69cab0f5e69a6c).
[30;1m2023-04-11 00:12:30[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command None
[31mdiscord.ext.commands.errors.CommandNotFound: Command "tt" is not found[0m
[30;1m2023-04-11 00:12:33[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 115, in start_ttt
    await ctx.send(file=discord.File('images/tictactoe_board_with_pieces.png'))
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\file.py", line 97, in __init__
    self.fp = open(fp, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/tictactoe_board_with_pieces.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'images/tictactoe_board_with_pieces.png'[0m
[2023-04-11 00:14:40] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:14:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:14:40] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:14:40[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:14:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: e933c4fa9ba3d03c667c229ddc6c4440).
[2023-04-11 00:17:52] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:17:52] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:17:52] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:17:52[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:17:53[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: dec5a8aaebd186c3de1645bde99a30f1).
[2023-04-11 00:20:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:20:29] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:20:29] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:20:29[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:20:30[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 13922adb8199acb664c034c02407bdfd).
[30;1m2023-04-11 00:20:38[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 114, in start_ttt
    message = await ctx("Your turn:\n" + tictactoe.print_board_discord())
TypeError: 'Context' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Context' object is not callable[0m
[30;1m2023-04-11 00:20:48[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 114, in start_ttt
    message = await ctx("Your turn:\n" + tictactoe.print_board_discord())
TypeError: 'Context' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Context' object is not callable[0m
[2023-04-11 00:21:03] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:21:03] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:21:03] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:21:03[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:21:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 1c4684b449d73c3eb12af9f554b519ca).
[30;1m2023-04-11 00:21:09[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 114, in start_ttt
    message = await ctx("Your turn:\n" + tictactoe.print_board_discord())
TypeError: 'Context' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Context' object is not callable[0m
[2023-04-11 00:21:43] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:21:43] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:21:43] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:21:43[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:21:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 23ee01cb34247839b4d7fc9a3d950a90).
[30;1m2023-04-11 00:21:49[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 114, in start_ttt
    message = await ctx("Your turn:\n" + tictactoe.print_board_discord())
TypeError: 'Context' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Context' object is not callable[0m
[2023-04-11 00:21:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:21:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:21:59] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:21:59[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:22:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 4e74654d5f246df0038ee350d2450fa1).
[2023-04-11 00:23:11] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:23:11] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:23:11] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:23:11[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:23:12[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 3ceeac50bcef121725fa10f70350689c).
[2023-04-11 00:24:35] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:24:35] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:24:35] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:24:35[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:24:36[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 04f594639313a5f275069f119376849a).
[2023-04-11 00:26:23] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:26:23] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:26:23] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:26:23[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:26:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 3237c3f921fd43bd58535442fb15d3bc).
[30;1m2023-04-11 00:26:36[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 153, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:28:34] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:28:34] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:28:34] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:28:34[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:28:35[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 45871864a082a2f7c5f1de83a2e53ecd).
[30;1m2023-04-11 00:28:43[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 169, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:29:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:29:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:29:59] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:29:59[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:30:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ef1433c61a6f32d0547637d887ef7432).
[30;1m2023-04-11 00:30:10[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 170, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:31:33] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:31:33] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:31:33] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:31:33[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:31:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: cd1f950fe0fff499d5a0289c0bb16362).
[30;1m2023-04-11 00:31:45[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 171, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:32:30] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:32:30] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:32:30] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:32:30[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:32:31[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 1c6e6c8fb2202748f58f477596807e13).
[30;1m2023-04-11 00:32:41[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 170, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:37:33] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:37:33] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:37:33] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:37:33[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:37:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 2428f62ee26b1f81fdde9cbe4629ba5a).
[30;1m2023-04-11 00:37:43[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 154, in start_ttt
    await board_ttt.edit(attachments=discord.File('images/tictactoe_board_with_piece.png'))
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\message.py", line 2168, in edit
    with handle_message_parameters(
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\http.py", line 231, in handle_message_parameters
    files = [a for a in attachments if isinstance(a, File)]
TypeError: 'File' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'File' object is not iterable[0m
[2023-04-11 00:45:01] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:45:01] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:45:01] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:45:01[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:45:02[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 6b749fff90095675c20f8a359ae9ae5b).
[30;1m2023-04-11 00:45:12[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 154, in start_ttt
    await ctx.add_files('images/tictactoe_board_with_piece.png')
AttributeError: 'Context' object has no attribute 'add_files'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Context' object has no attribute 'add_files'[0m
[2023-04-11 00:46:38] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:46:38] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:46:38] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:46:38[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:46:39[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 325424be02b390287b8949986049f5e4).
[30;1m2023-04-11 00:46:50[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 154, in start_ttt
    await ctx.system_content(file=discord.File('images/tictactoe_board_with_piece.png'))
AttributeError: 'Context' object has no attribute 'system_content'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Context' object has no attribute 'system_content'[0m
[2023-04-11 00:47:05] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:47:05] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:47:05] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:47:05[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:47:06[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: fba8f8b6fc67277ae6a8ffb4caa5d40b).
[30;1m2023-04-11 00:47:22[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 102, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 170, in start_ttt
    await board_ttt.edit(file=discord.File('images/tictactoe_board_with_piece.png'))
TypeError: edit() got an unexpected keyword argument 'file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: edit() got an unexpected keyword argument 'file'[0m
[2023-04-11 00:48:37] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:48:37] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:48:37] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:48:37[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:48:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: f1f076638802f595466fb35ef36cea26).
[2023-04-11 00:54:42] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 00:54:42] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 00:54:42] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 00:54:42[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 00:54:43[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 9305cc8972065a90541dbfc21f9cd4a3).
[2023-04-11 01:00:10] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:00:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:00:10] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:00:10[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:00:11[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ea1f3a9d1a53f539ba6f2a3659488c2c).
[2023-04-11 01:01:50] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:01:50] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:01:50] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:01:50[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:01:51[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 5fd021d467d5124efbf27745d157d8d7).
[2023-04-11 01:02:36] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:02:36] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:02:36] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:02:36[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:02:37[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 42e77525db372aa3ae0e3e8222b12440).
[2023-04-11 01:03:49] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:03:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:03:49] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:03:49[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:03:50[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: d3a52c0032643c471265b4a94407da77).
[2023-04-11 01:04:28] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:04:28] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:04:28] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:04:28[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:04:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 6402972a642c9f2b55c0246ca09c66cb).
[2023-04-11 01:09:45] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:09:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:09:45] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:09:45[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:09:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: fe590721702612460a03be1baed914ea).
[2023-04-11 01:12:33] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:12:33] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:12:33] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:12:33[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:12:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 430ad5c5bc66484f67f4702b24c9ae19).
[2023-04-11 01:14:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:14:51] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:14:51] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:14:51[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:14:52[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: cc7af76af5feabf46203cafa95bd0838).
[2023-04-11 01:17:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:17:29] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:17:29] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:17:29[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:17:30[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: f81f6e3cf6e466598e48ab800ae2da87).
[2023-04-11 01:18:23] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:18:23] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:18:23] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:18:23[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:18:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: b48ffe77868ed7395ce79fd9fe241e71).
[2023-04-11 01:20:16] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:20:16] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:20:16] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:20:16[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:20:17[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 83a4955bfc8cb8b184191d083bdd009a).
[30;1m2023-04-11 01:20:20[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command None
[31mdiscord.ext.commands.errors.CommandNotFound: Command "tt" is not found[0m
[2023-04-11 01:21:19] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:21:19] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:21:19] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:21:19[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:21:20[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 435968e258cce6e6f3e7fa0180450e08).
[2023-04-11 01:21:37] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:21:37] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:21:37] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:21:37[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:21:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 755a0159860754c5f6578bbf05bba6f1).
[2023-04-11 01:22:40] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:22:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:22:40] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:22:40[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:22:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ace0bf7d1e74ad4002c459c61c959d4b).
[2023-04-11 01:24:32] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:24:32] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:24:32] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:24:32[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:24:32[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 1e6687fff89c32f579c60ea3a21942ad).
[2023-04-11 01:25:13] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:25:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:25:13] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:25:13[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:25:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ab87f930c8ab9849c1db585d4bf92485).
[2023-04-11 01:26:02] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:26:02] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:26:02] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:26:02[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:26:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: e138c66d83b918d87d22768aaef24e6f).
[2023-04-11 01:27:46] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:27:46] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:27:46] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:27:46[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:27:47[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: f3cb82efb2e5d75ddf86de21c1fceaa7).
[2023-04-11 01:29:45] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:29:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:29:45] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:29:45[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:29:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 7fadd66b5e80b5c870c3cebfb457a526).
[2023-04-11 01:50:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:50:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:50:21] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:50:21[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:50:21[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: bc9908845b12398d9ad4256084b70dd2).
[2023-04-11 01:52:33] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:52:33] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:52:33] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:52:33[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:52:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 564d1ba73913eb28942f7d34e835bafb).
[30;1m2023-04-11 01:53:19[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 108, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 197, in start_ttt
    tictactoe.draw_line(tictactoe.win_position(tictactoe.board, tictactoe.computer))
TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'[0m
[2023-04-11 01:59:57] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 01:59:57] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 01:59:57] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 01:59:57[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 01:59:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 85947a0d300623f2328a5975cb62651b).
[2023-04-11 02:02:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:02:21] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:02:21] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:02:21[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:02:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: de120cfab477c6a9c439e0794f9b0a7a).
[2023-04-11 02:04:09] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:04:09] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:04:09] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:04:09[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:04:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 7fae38d090ef14c0ee2252bd84dcd3d5).
[30;1m2023-04-11 02:04:41[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 108, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 197, in start_ttt
    tictactoe.draw_line(tictactoe.win_position(tictactoe.board, tictactoe.computer))
TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'[0m
[2023-04-11 02:10:10] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:10:10] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:10:10] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:10:10[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:10:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 39a579efff355be763715a0b2fddb69a).
[30;1m2023-04-11 02:10:48[0m [31mERROR   [0m [35mdiscord.ext.commands.bot[0m Ignoring exception in command play_tictactoe
[31mTraceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 108, in play_tictactoe
    await start_ttt(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\bot.py", line 197, in start_ttt
    tictactoe.draw_line(tictactoe.win_position(tictactoe.board, tictactoe.computer))
TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Mateusz\Desktop\jpwpBotDiscord\venvdada\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: draw_line() missing 3 required positional arguments: 'col1', 'row2', and 'col2'[0m
[2023-04-11 02:11:26] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:11:26] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:11:26] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:11:26[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:11:27[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 4b5eb4909f21f8914c5d3da0064870ef).
[2023-04-11 02:12:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:12:59] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:12:59] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:12:59[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[2023-04-11 02:13:05] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:13:05] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:13:05] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:13:05[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:13:06[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: b7cab2959334a8a37bf26504fe0eccf8).
[2023-04-11 02:18:55] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:18:55] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:18:55] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:18:55[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:18:56[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: b0c7d760aca26ee1a6fdeea2cc223cf1).
[2023-04-11 02:30:35] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:30:35] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:30:35] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:30:35[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:30:36[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 49b0238a52db6c1bfb31b5dabc14e21d).
[2023-04-11 02:33:49] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:33:49] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:33:49] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:33:49[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:33:50[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 4eee49ea5c2b8696e73d4d27c2a8e83c).
[2023-04-11 02:36:32] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:36:32] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:36:32] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:36:32[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:36:33[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: ee136affab2d69b381e56417a8d3cbea).
[2023-04-11 02:38:45] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:38:45] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:38:45] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:38:45[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:38:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: e74c62120b337256af61051b2be1518c).
[2023-04-11 02:41:23] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 02:41:23] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 02:41:23] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 02:41:23[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 02:41:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 3aba624dc8940433f03f00385393ffc3).
[2023-04-11 21:29:40] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2023-04-11 21:29:40] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-04-11 21:29:40] [DEBUG   ] discord.client: on_message has successfully been registered as an event
[30;1m2023-04-11 21:29:40[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-04-11 21:29:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 2e81fcde2cb4868fd5dfbe09e31feb22).
